lessons:
  outputs:
    dev:
      dataset: dbt_per
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: glass-flux-466005-m4
      threads: 60
      type: bigquery
  target: dev
